[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "report generator"
authors = [{name = "Mayank Sharma", email = "mayank@codeops.tech"}]
dynamic = ["version", "description"]